# Generated by Django 5.2.6 on 2025-09-25 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_alter_track_name'),
        ('trainee', '0002_remove_trainee_email_trainee_age_alter_trainee_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='age',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='track',
        ),
        migrations.AddField(
            model_name='trainee',
            name='email',
            field=models.EmailField(default='python', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainee',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='trackid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='track.track'),
        ),
    ]
