# Generated by Django 5.2.6 on 2025-09-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_remove_trainee_age_remove_trainee_track_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
